### ISSUE TITLE
Tab cannot be closed by middle click

### ISSUE THREAD

**Issue by Naezr** [Tagggar/Firefox-Alpha#3]
When you press the middle mouse button on the active tab, the address bar opens

**Comment by Tagggar** [comment]
In the current implementation of the [Combined Tab and Urlbar](https://github.com/Tagggar/Firefox-Alpha#combined-tab-and-urlbar), you can't use the `MMB` (middle mouse button) to close the active tab. As of now, there isn't a known working workaround that I'm aware of. Do you have any ideas?

To close Active Tab you can:

`LMB` \ `MMB` on the ❌ (close tab icon);

`MMB` on favicon of the tab;

Functional modifications are very limited due to the current constraints. We are unable to alter the browser's source code; only visual changes using CSS are possible.

However, the functionality achieved through CSS and certain extensions is already quite impressive, in my opinion.

Perhaps, in the future, Firefox developers will incorporate this feature natively.

**Comment by dmbarrad** [comment]
The Firefox developers are the worst. After the latest update (123), I can't even click the tabs. Before this update, Everything worked perfect, And I mean perfectesimo.
