### ISSUE TITLE
Unable to drag and move tabs

### ISSUE THREAD

**Issue by Tanish2002** [Tagggar/Firefox-Alpha#7]
It isn't possible to move tabs using the mouse. Whenever I click on a tab and try to drag it, it just opens the URL/Search bar.
Do I need some plugin to move tabs?

**Comment by tamalCodes** [comment]
This was weird to me at first too, Click on the icons of the websites, and drag. That will work.
Please watch this abridged recording: [Watch video (this video has no sound)](https://www.loom.com/share/bb9175b0776c470ca4c5e74d059677c1?sid=4350a7a3-2476-4501-ace9-e66b569e71df)

**Comment by Tanish2002** [comment]
Yeah that seems to work. It's kinda buggy and doesn't work sometimes but I'm fine with it. Thanks!

**Comment by Tagggar** [comment]
Hi, and sorry for the late reply.

You can move the tab by selecting the favicon and dragging it within the horizontal row. Refer to the video for a visual guide: 

https://github.com/Tagggar/Firefox-Alpha/assets/81634877/b49803b3-d025-4ef8-8925-afa6ae6d91d8

Additionally, you can move the Tab by: `RMB` > `Move Tab` > `Move to Start`.

Please note that there's a slight bug at the moment, likely due to interference from multiple components.
